# Generated by Django 4.2.16 on 2024-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_pickup_return_remove_invoice_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="qr_code_image",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="qr_codes/"
            ),
        ),
    ]
