# Generated by Django 4.2.16 on 2024-10-27 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="status",
        ),
    ]
