# Generated by Django 4.2.16 on 2024-10-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_driver_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_warehouse", "In Warehouse"),
                    ("in_transit", "In Transit"),
                    ("in_store", "In Store"),
                    ("sold", "Sold"),
                ],
                default="in_warehouse",
                max_length=20,
            ),
        ),
    ]
