# Generated by Django 4.2.16 on 2024-11-03 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_driver_profile_picture_alter_driver_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickup",
            name="dropoff_time",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="pickup_time",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="product",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="status",
        ),
        migrations.RemoveField(
            model_name="pickup",
            name="store",
        ),
        migrations.RemoveField(
            model_name="return",
            name="pickup_time",
        ),
        migrations.RemoveField(
            model_name="return",
            name="product",
        ),
        migrations.RemoveField(
            model_name="return",
            name="return_time",
        ),
        migrations.RemoveField(
            model_name="return",
            name="status",
        ),
        migrations.AddField(
            model_name="pickup",
            name="products",
            field=models.ManyToManyField(to="api.product"),
        ),
        migrations.AddField(
            model_name="return",
            name="products",
            field=models.ManyToManyField(to="api.product"),
        ),
        migrations.CreateModel(
            name="DropOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dropoff_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoffs",
                        to="api.pickup",
                    ),
                ),
                ("products", models.ManyToManyField(to="api.product")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.store"
                    ),
                ),
            ],
        ),
    ]
