# Generated by Django 4.2.16 on 2024-11-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_pickup_dropoff_time_remove_pickup_pickup_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.driver",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.store",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.warehouse",
            ),
        ),
    ]
