# Generated by Django 4.2.16 on 2024-11-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_driver_created_at_dropoff_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dropoff",
            name="pickup",
        ),
        migrations.AddField(
            model_name="dropoff",
            name="driver",
            field=models.ForeignKey(
                default=23,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dropoffs",
                to="api.driver",
            ),
            preserve_default=False,
        ),
    ]
