# Generated by Django 4.2.16 on 2024-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_remove_dropoff_pickup_dropoff_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="box_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
