# Generated by Django 4.2.16 on 2024-11-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_product_box_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_warehouse", "In Warehouse"),
                    ("in_transit", "In Transit"),
                    ("in_return_transit", "In Return Transit"),
                    ("in_store", "In Store"),
                    ("sold", "Sold"),
                ],
                default="in_warehouse",
                max_length=20,
            ),
        ),
    ]
