# Generated by Django 4.2.16 on 2024-11-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="products",
            field=models.ManyToManyField(related_name="returns", to="api.product"),
        ),
    ]
