# Generated by Django 4.2.16 on 2024-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="iqama_number",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="driving_license_expiry_date",
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
