# Generated by Django 4.2.16 on 2024-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_rename_iqama_number_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropoff",
            name="method_of_collection",
            field=models.CharField(
                choices=[("CASH", "CASH"), ("POS", "POS")],
                default="CASH",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="dropoff",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("cash_collected", "Cash Collected"),
                ],
                default="initiated",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="dropoff",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
