# Generated by Django 4.2.16 on 2024-11-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_dropoff_method_of_collection_dropoff_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                ("date_issued", models.DateField()),
                ("seller_name", models.CharField(max_length=255)),
                ("seller_vat_number", models.CharField(max_length=20)),
                ("buyer_name", models.CharField(max_length=255)),
                ("buyer_vat_number", models.CharField(max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
    ]
