# Generated by Django 4.2.16 on 2024-11-17 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
