# Generated by Django 4.2.16 on 2024-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_pickup_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickup",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
